name: code quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RuboCop
        run: rubocop Formula/ --display-cop-names --extra-details || true
      - name: Run Reek
        run: reek Formula/ || true
      - name: Run Fasterer
        run: fasterer Formula/ || true
